name: momentclient
description: 野火朋友圈SDK
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  imclient:
    path: ../imclient/

  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
