#!/usr/bin/env python3
"""从 wfc_functions.json（WFClient.h 的机读签名）生成 dart:ffi 绑定。

用法：python3 gen_ffi_bindings.py > ../lib/src/ffi/wfclient_bindings.dart

签名映射规则：
- 所有 279 个函数全部生成，`late final` 惰性 lookup——当前动态库缺失的符号
  只有在真正调用时才会抛错，不影响其他功能。
- 回调 typedef 映射为 Pointer<NativeFunction<...>>，具体签名见 _CALLBACKS。
- WFCAPI(__stdcall) 仅影响 win32(ia32)；Flutter Windows 仅 x64/arm64，与
  cdecl 一致，无需 Abi 特化。
"""
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).parent
FUNCS = json.loads((HERE / 'wfc_functions.json').read_text())

# 回调 typedef → (native 签名, 注释)
CALLBACKS = {
    'fun_global_string_callback': 'Void Function(Pointer<Char>, Size)',
    'fun_global_int_int_callback': 'Void Function(Int32, Int32)',
    'fun_global_int_sring_callback': 'Void Function(Int32, Pointer<Char>, Size)',
    'fun_global_void_callback': 'Void Function()',
    'fun_connection_callback': 'Void Function(Int32)',
    'fun_receive_message_callback': 'Void Function(Pointer<Char>, Size, Bool)',
    'fun_recall_message_callback': 'Void Function(Pointer<Char>, Size, Int64)',
    'fun_delete_message_callback': 'Void Function(Int64)',
    'fun_connecting_to_server_callback':
        'Void Function(Pointer<Char>, Size, Pointer<Char>, Size)',
    'fun_connected_to_server_callback':
        'Void Function(Pointer<Char>, Size, Pointer<Char>, Size, Int32)',
    'fun_general_void_success_callback': 'Void Function(Pointer<Void>, Int32)',
    'fun_general_string_success_callback':
        'Void Function(Pointer<Void>, Int32, Pointer<Char>, Size)',
    'fun_general_error_callback': 'Void Function(Pointer<Void>, Int32, Int32)',
    'fun_sendMessage_success_callback':
        'Void Function(Pointer<Void>, Int32, Long, Int64, Int64)',
    'fun_sendMessage_prepared_callback':
        'Void Function(Pointer<Void>, Int32, Long, Int64)',
    'fun_sendMessage_progress_callback':
        'Void Function(Pointer<Void>, Int32, Long, Int32, Int32)',
    'fun_sendMessage_media_uploaded_callback':
        'Void Function(Pointer<Void>, Int32, Long, Pointer<Char>, Size)',
    'fun_sendMessage_error_callback':
        'Void Function(Pointer<Void>, Int32, Long, Int32)',
    'fun_uploadMedia_progress_callback':
        'Void Function(Pointer<Void>, Int32, Int32, Int32)',
}

NATIVE_TO_DART = {
    'Void': 'void', 'Int32': 'int', 'Int64': 'int', 'Long': 'int',
    'Size': 'int', 'Bool': 'bool',
}


def map_type(ctype: str):
    """C 类型 → (native ffi 类型, dart 类型)。"""
    t = ctype.strip()
    if t in CALLBACKS:
        p = f'Pointer<NativeFunction<{CALLBACKS[t]}>>'
        return p, p
    if re.match(r'^const int \w+\[\]$', t) or t == 'const int*':
        return 'Pointer<Int32>', 'Pointer<Int32>'
    if re.match(r'^const int64_t \w+\[\]$', t):
        return 'Pointer<Int64>', 'Pointer<Int64>'
    table = {
        'void': ('Void', 'void'),
        'bool': ('Bool', 'bool'),
        'int': ('Int32', 'int'),
        'int WFCAPI': ('Int32', 'int'),
        'int64_t': ('Int64', 'int'),
        'long': ('Long', 'int'),
        'long long': ('Int64', 'int'),
        'size_t': ('Size', 'int'),
        'size_t *': ('Pointer<Size>', 'Pointer<Size>'),
        'const size_t*': ('Pointer<Size>', 'Pointer<Size>'),
        'const char *': ('Pointer<Char>', 'Pointer<Char>'),
        'const char*': ('Pointer<Char>', 'Pointer<Char>'),
        'const char**': ('Pointer<Pointer<Char>>', 'Pointer<Pointer<Char>>'),
        'const unsigned char *': ('Pointer<UnsignedChar>', 'Pointer<UnsignedChar>'),
        'void *': ('Pointer<Void>', 'Pointer<Void>'),
    }
    if t not in table:
        raise SystemExit(f'unmapped C type: {t!r}')
    return table[t]


def parse_args(argstr: str):
    if not argstr or argstr.strip() in ('void', ''):
        return []
    out = []
    for a in argstr.split(','):
        a = a.strip()
        # 数组形参：类型含名字
        m = re.match(r'^(const int(?:64_t)?) (\w+)\[\]$', a)
        if m:
            out.append((f'{m.group(1)} {m.group(2)}[]', m.group(2)))
            continue
        m = re.match(r'^(.*?)([A-Za-z_]\w*)$', a)
        ctype, name = m.group(1).strip(), m.group(2)
        out.append((ctype, name))
    return out


lines = [
    '// GENERATED by scripts/gen_ffi_bindings.py from scripts/wfc_functions.json',
    '// （源头是 marslib/include/WFClient.h）。请勿手工修改；接口变更后重新生成。',
    '// ignore_for_file: non_constant_identifier_names',
    "import 'dart:ffi';",
    '',
]
for name, sig in CALLBACKS.items():
    lines.append(f'typedef Native_{name} = {sig};')
lines += [
    '',
    '/// WFClient C API 绑定。所有函数惰性解析：动态库中缺失的符号只在调用时报错。',
    'class WFClientBindings {',
    '  WFClientBindings(this._lib);',
    '',
    '  final DynamicLibrary _lib;',
    '',
]

seen = set()
for f in FUNCS:
    name = f['name']
    if name in seen:
        continue
    seen.add(name)
    ret_native, ret_dart = map_type(f['return'])
    args = parse_args(f['args'])
    natives, darts = [], []
    for ctype, _argname in args:
        n, d = map_type(ctype)
        natives.append(n)
        darts.append(d)
    native_sig = f'{ret_native} Function({", ".join(natives)})'
    dart_sig = f'{ret_dart} Function({", ".join(darts)})'
    lines.append(
        f'  late final {ret_dart} Function({", ".join(darts)}) {name} =\n'
        f'      _lib.lookupFunction<{native_sig}, {dart_sig}>(\'{name}\');')
    lines.append('')
lines.append('}')
sys.stdout.write('\n'.join(lines) + '\n')
